version: 2
jobs:
  build:
    docker:
      - image: crystallang/crystal:nightly # docker:stable-git
    environment:
      CRYSTAL_VERSION: "0.24.2" # "0.20.1" # Replace version to which you're using
      PATH: "${PATH}:${HOME}/.crystal/bin"
      CRYSTAL_URL: "https://github.com/crystal-lang/crystal/releases/download/${CRYSTAL_VERSION}/crystal-${CRYSTAL_VERSION}-1-linux-x86_64.tar.gz"
    steps:
      - checkout
      - run:
          - name: update_deps
          - command: shards update
      - run:
          - name: build_deps
          - command: shards build
      - run:
          - name: test
          - command: crystal spec
      - save_cache:
        key: dependency-cache
        paths:
          - .shards
    dependencies:
      cache_directories:
        - ~/.crystal
        - lib
        - .shards
      pre:
        - |
          if [[ ! -e "${HOME}/.crystal/bin/crystal" || $(crystal --version | grep -P -o '\d+\.\d+\.\d+') != "${CRYSTAL_VERSION}" ]]; then
            mkdir "${HOME}/.crystal"
            wget "${CRYSTAL_URL}" -O "${HOME}/crystal.tar.gz" &&\
            tar -zxvf "${HOME}/crystal.tar.gz" -C "${HOME}/.crystal" --strip-components=1
          fi
      # override:
      #   - crystal deps
    # test:
    #   override:
    #     - crystal spec

  